package com.ingelecron.proyectoandroid.tiposDatos;


public enum TipoPais {


    Pais ("+ agregar país"),
    P1 ("Afganistán"),
    P2 ("Albania"),
    P3 ("Alemania"),
    P4 ("Angola"),
    P5 ("Anguila"),
    P6 ("Antigua y Barbuda"),
    P7 ("Antillas Holandesas"),
    P8 ("Arabia Saudita"),
    P9 ("Argelia"),
    P10 ("Argentina"),
    P11 ("Armenia"),
    P12 ("Aruba"),
    P13 ("Australia"),
    P14 ("Austria"),
    P15 ("Azerbaiyán"),
    P16 ("Bahamas"),
    P17 ("Bangladés"),
    P18 ("Barbados"),
    P19 ("Bélgica"),
    P20 ("Belice"),
    P21 ("Benín"),
    P22 ("Bermudas"),
    P23 ("Bielorrusia"),
    P24 ("Bolivia"),
    P25 ("Bosnia y Herzegovina"),
    P26 ("Botsuana"),
    P27 ("Brasil"),
    P28 ("Brunéi"),
    P29 ("Bulgaria"),
    P30 ("Burkina Faso"),
    P31 ("Burundi"),
    P32 ("Bután"),
    P33 ("Cabo Verde"),
    P34 ("Camboya"),
    P35 ("Camerún"),
    P36 ("Canadá"),
    P37 ("Catar"),
    P38 ("Chad"),
    P39 ("Chequia"),
    P40 ("Chile"),
    P41 ("China"),
    P42 ("Chipre"),
    P43 ("Colombia"),
    P44 ("Comoras"),
    P45 ("Congo"),
    P46 ("Corea"),
    P47 ("Corea del Norte"),
    P48 ("Costa de Marfil"),
    P49 ("Costa Rica"),
    P50 ("Croacia"),
    P51 ("Cuba"),
    P52 ("Diego Garcia"),
    P53 ("Dinamarca"),
    P54 ("Dominica"),
    P55 ("Ecuador"),
    P56 ("Egipto"),
    P57 ("El Salvador"),
    P58 ("Emiratos Árabes Unidos"),
    P59 ("Eritrea"),
    P60 ("Escocia"),
    P61 ("Eslovaquia"),
    P62 ("Eslovenia"),
    P63 ("España"),
    P64 ("Estonia"),
    P65 ("Etiopía"),
    P66 ("Filipinas"),
    P67 ("Finlandia"),
    P68 ("Flyi"),
    P69 ("Francia"),
    P70 ("Gabón"),
    P71 ("Gales"),
    P72 ("Gambia"),
    P73 ("Georgia"),
    P74 ("Ghana"),
    P75 ("Gibraltar"),
    P76 ("Granada"),
    P77 ("Grecia"),
    P78 ("Groenlandia"),
    P79 ("Guadalupe"),
    P80 ("Guam"),
    P81 ("Guatemala"),
    P82 ("Guyana Francesa"),
    P83 ("Guinea"),
    P84 ("Guinea Ecuatorial"),
    P85 ("Guinea-Bissau"),
    P86 ("Guyana"),
    P87 ("Haití"),
    P88 ("Holanda"),
    P89 ("Honduras"),
    P90 ("Hong Kong"),
    P91 ("Hungría"),
    P92 ("India"),
    P93 ("Indonesia"),
    P94 ("Inglaterra"),
    P95 ("Irak"),
    P96 ("Irán"),
    P97 ("Irlanda"),
    P98 ("Irlanda del Norte"),
    P99 ("Isla Ascensión"),
    P100 ("Isla Norfolk"),
    P101 ("Islandia"),
    P102 ("Islas Caimán"),
    P103 ("Islas Cook"),
    P104 ("Islas Feroe"),
    P105 ("Islas Malvinas"),
    P106 ("Islas Marianas del Norte"),
    P107 ("Islas Marshall"),
    P108 ("Islas Salomón"),
    P109 ("Islas Turcas y Caicos"),
    P110 ("Islas Vírgenes Británicas"),
    P111 ("Islas Vírgenes Americanas"),
    P112 ("Israel"),
    P113 ("Italia"),
    P114 ("Jamaica"),
    P115 ("Japón"),
    P116 ("Jordania"),
    P117 ("Kazajistán"),
    P118 ("Kenia"),
    P119 ("Kirguistán"),
    P120 ("Kiribati"),
    P121 ("Kuwait"),
    P122 ("Laos"),
    P123 ("Lesoto"),
    P124 ("Letonia"),
    P125 ("Líbano"),
    P126 ("Liberia"),
    P127 ("Libia"),
    P128 ("Liechtenstein"),
    P129 ("Lituania"),
    P130 ("Luxemburgo"),
    P131 ("Macao"),
    P132 ("Macedonia"),
    P133 ("Madagascar"),
    P134 ("Malasia"),
    P135 ("Malaui"),
    P136 ("Maldivas"),
    P137 ("Malí"),
    P138 ("Malta"),
    P139 ("Marruecos"),
    P140 ("Martinica"),
    P141 ("Mauricio"),
    P142 ("Mauritania"),
    P143 ("Mayotte"),
    P144 ("México"),
    P145 ("Micronesia"),
    P146 ("Moldavia"),
    P147 ("Mónaco"),
    P148 ("Mongolia"),
    P149 ("Montenegro"),
    P150 ("Montserrat"),
    P151 ("Mozambique"),
    P152 ("Myanmar"),
    P153 ("Namibia"),
    P154 ("Nauru"),
    P155 ("Nepal"),
    P156 ("Nicaragua"),
    P157 ("Níger"),
    P158 ("Nigeria"),
    P159 ("Niue"),
    P160 ("Noruega"),
    P161 ("Nueva Caledonia"),
    P162 ("Nueva Zelanda"),
    P163 ("Omán"),
    P164 ("Pakistán"),
    P165 ("Palaos"),
    P166 ("Palestina"),
    P167 ("Panamá"),
    P168 ("Papúa Nueva Guinea"),
    P169 ("Paraguay"),
    P170 ("Perú"),
    P171 ("Polinesia Francesa"),
    P172 ("Polonia"),
    P173 ("Portugal"),
    P174 ("Principado de Andorra"),
    P175 ("Puerto Rico"),
    P176 ("Reino de Bahréin"),
    P177 ("República Dominicana"),
    P178 ("República Centroafricana"),
    P179 ("República Democrática del Congo"),
    P180 ("Reunión"),
    P181 ("Ruanda"),
    P182 ("Rumania"),
    P183 ("Rusia"),
    P184 ("Sáhara Occidental"),
    P185 ("Samoa"),
    P186 ("Samoa Americana"),
    P187 ("San Bartolomé"),
    P188 ("San Cristóbal y Nieves"),
    P189 ("San Marino"),
    P190 ("San Martin"),
    P191 ("San Pedro y Miquelón"),
    P192 ("San Vicente y las Granadinas"),
    P193 ("Santa Elena"),
    P194 ("Santa Lucía"),
    P195 ("Santo Tomé y Príncipe"),
    P196 ("Satélite Inmarsat"),
    P197 ("Satélite Iridium"),
    P198 ("Satélite Thuraya"),
    P199 ("Senegal"),
    P200 ("Serbia"),
    P201 ("Seychelles"),
    P202 ("Sierra Leona"),
    P203 ("Singapur"),
    P204 ("Sint Maarten"),
    P205 ("Siria"),
    P206 ("Somalia"),
    P207 ("Sri Lanka"),
    P208 ("Suazilandia"),
    P209 ("Sudáfrica"),
    P210 ("Sudán"),
    P211 ("Sudán del Sur"),
    P212 ("Suecia"),
    P213 ("Suiza"),
    P214 ("Surinam"),
    P215 ("Tailandia"),
    P216 ("Taiwán"),
    P217 ("Tanzania"),
    P218 ("Tayikistán"),
    P219 ("Timor Oriental"),
    P220 ("Togo"),
    P221 ("Tokelau"),
    P222 ("Tonga"),
    P223 ("Trinidad y Tobago"),
    P224 ("Túnez"),
    P225 ("Turkmenistán"),
    P226 ("Turquía"),
    P227 ("Tuvalu"),
    P228 ("Ucrania"),
    P229 ("Uganda"),
    P230 ("Uruguay"),
    P231 ("USA"),
    P232 ("Uzbekistán"),
    P233 ("Vanuatu"),
    P234 ("Vaticano"),
    P235 ("Venezuela"),
    P236 ("Vietnam"),
    P237 ("Wallis y Futuna"),
    P238 ("Yemen"),
    P239 ("Yibuti"),
    P240 ("Zambia"),
    P241 ("Zimbabue");

    private final String texto;

    TipoPais(String texto) {
        this.texto = texto;
    }

    public String getTextoPais() { return texto; }

    public static String[] getDatosPais() {

        String[] resultado = new String[TipoPais.values().length];

        for (TipoPais pais : TipoPais.values()) {
            resultado[pais.ordinal()] = pais.texto;
        }

        return resultado;
    }

}
